# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib lavaanrust, .registration = TRUE
NULL

#' Fit the covariance-only one-factor DWLS slice used by GenomicSEM's
#' `commonfactor()` model.
#'
#' `sample_cov` and `wls_v` are flattened column-major R matrices.
#' @export
fit_one_factor_dwls <- function(sample_cov, wls_v, n, max_iter, tol) .Call(wrap__fit_one_factor_dwls, sample_cov, wls_v, n, max_iter, tol)

# nolint end
