#ifndef GENOMICSSEM_NATIVE_H
#define GENOMICSSEM_NATIVE_H

#include <stddef.h>

int genomicssem_fill_v_snp(
    const double *se_snp,
    size_t se_nrow,
    size_t se_ncol,
    size_t i_zero,
    const double *i_ld,
    size_t i_ld_nrow,
    size_t i_ld_ncol,
    const double *var_snp,
    size_t var_snp_len,
    const int *coords,
    size_t coords_nrow,
    size_t coords_ncol,
    size_t k,
    int gc_code,
    double *out,
    size_t out_len);

int genomicssem_fill_v_full(
    size_t k,
    const double *v_ld,
    size_t v_ld_nrow,
    size_t v_ld_ncol,
    double var_snp_se2,
    const double *v_snp,
    size_t v_snp_nrow,
    size_t v_snp_ncol,
    double *out,
    size_t out_len);

int genomicssem_fill_v_snp_batch(
    const double *se_snp,
    size_t se_nrow,
    size_t se_ncol,
    const double *i_ld,
    size_t i_ld_nrow,
    size_t i_ld_ncol,
    const double *var_snp,
    size_t var_snp_len,
    const int *coords,
    size_t coords_nrow,
    size_t coords_ncol,
    size_t k,
    int gc_code,
    size_t n_threads,
    double *out,
    size_t out_len);

int genomicssem_fill_s_full(
    size_t k,
    const double *s_ld,
    size_t s_ld_nrow,
    size_t s_ld_ncol,
    const double *var_snp,
    size_t var_snp_len,
    const double *beta_snp,
    size_t beta_nrow,
    size_t beta_ncol,
    size_t i_zero,
    double *out,
    size_t out_len);

int genomicssem_fill_z_pre(
    const double *beta_snp,
    size_t beta_nrow,
    size_t beta_ncol,
    const double *se_snp,
    size_t se_nrow,
    size_t se_ncol,
    const double *i_ld,
    size_t i_ld_nrow,
    size_t i_ld_ncol,
    size_t i_zero,
    int gc_code,
    double *out,
    size_t out_len);

int genomicssem_fit_commonfactor_main(
    size_t k,
    const double *s_full,
    size_t s_nrow,
    size_t s_ncol,
    const double *v_full_reorder,
    size_t v_nrow,
    size_t v_ncol,
    const double *w_diag,
    size_t w_len,
    const double *start,
    size_t start_len,
    size_t max_iter,
    double tol,
    double *out,
    size_t out_len);

int genomicssem_fit_commonfactor_q(
    size_t k,
    const double *s_full,
    size_t s_nrow,
    size_t s_ncol,
    const double *v_full_reorder,
    size_t v_nrow,
    size_t v_ncol,
    const double *w_diag,
    size_t w_len,
    const double *fixed,
    size_t fixed_len,
    const double *start,
    size_t start_len,
    size_t max_iter,
    double tol,
    double *out,
    size_t out_len);

int genomicssem_fit_commonfactor_batch(
    size_t k,
    const double *s_ld,
    size_t s_ld_nrow,
    size_t s_ld_ncol,
    const double *v_ld,
    size_t v_ld_nrow,
    size_t v_ld_ncol,
    const double *i_ld,
    size_t i_ld_nrow,
    size_t i_ld_ncol,
    const double *beta_snp,
    size_t beta_nrow,
    size_t beta_ncol,
    const double *se_snp,
    size_t se_nrow,
    size_t se_ncol,
    const double *var_snp,
    size_t var_snp_len,
    const int *coords,
    size_t coords_nrow,
    size_t coords_ncol,
    double var_snp_se2,
    int gc_code,
    const double *start,
    size_t start_len,
    size_t max_iter_main,
    size_t max_iter_q,
    double tol,
    size_t n_threads,
    double *out,
    size_t out_len);

int genomicssem_fit_generic_sem(
    size_t obs_n,
    size_t total_n,
    const double *s_full,
    size_t s_nrow,
    size_t s_ncol,
    const double *v_full_reorder,
    size_t v_nrow,
    size_t v_ncol,
    const double *w_diag,
    size_t w_len,
    const double *b_fixed,
    size_t b_fixed_len,
    const double *psi_fixed,
    size_t psi_fixed_len,
    const int *b_free,
    size_t b_free_len,
    const int *psi_free,
    size_t psi_free_len,
    const double *start,
    size_t start_len,
    size_t max_iter,
    double tol,
    double *out,
    size_t out_len);

int genomicssem_fit_generic_sem_batch(
    size_t obs_n,
    size_t total_n,
    const double *s_ld,
    size_t s_ld_nrow,
    size_t s_ld_ncol,
    const double *v_ld,
    size_t v_ld_nrow,
    size_t v_ld_ncol,
    const double *i_ld,
    size_t i_ld_nrow,
    size_t i_ld_ncol,
    const double *beta_snp,
    size_t beta_nrow,
    size_t beta_ncol,
    const double *se_snp,
    size_t se_nrow,
    size_t se_ncol,
    const double *var_snp,
    size_t var_snp_len,
    const int *coords,
    size_t coords_nrow,
    size_t coords_ncol,
    double var_snp_se2,
    int gc_code,
    const int *order,
    size_t order_len,
    const int *spec_to_original,
    size_t spec_to_original_len,
    const double *b_fixed,
    size_t b_fixed_len,
    const double *psi_fixed,
    size_t psi_fixed_len,
    const int *b_free,
    size_t b_free_len,
    const int *psi_free,
    size_t psi_free_len,
    const double *start,
    size_t start_len,
    const int *q_snp_indices,
    size_t q_snp_nrow,
    size_t q_snp_ncol,
    const int *q_snp_lengths,
    size_t q_snp_lengths_len,
    size_t max_iter,
    double tol,
    size_t n_threads,
    double *out,
    size_t out_len);

int genomicssem_munge_qc(
    const int *a1_ref,
    const int *a2_ref,
    const int *a1_file,
    const int *a2_file,
    const double *effect,
    const double *p,
    size_t n,
    const double *info,
    size_t info_len,
    const double *maf,
    size_t maf_len,
    double info_filter,
    double maf_filter,
    int *keep,
    double *z,
    size_t out_len,
    int *counts,
    size_t counts_len,
    size_t *out_count);

int genomicssem_munge_fused(
    const char *filename,
    const char *output_path,
    const char **ref_snp,
    size_t ref_len,
    const int *ref_a1,
    size_t ref_a1_len,
    const int *ref_a2,
    size_t ref_a2_len,
    const int *col_indices,
    size_t col_indices_len,
    double provided_n,
    double n_multiplier,
    double info_filter,
    double maf_filter,
    int *out_counts,
    size_t out_counts_len,
    size_t *rows_total,
    size_t *rows_joined,
    size_t *rows_written,
    int *unsupported);

int genomicssem_sumstats_qc(
    const int *a1_ref,
    const int *a2_ref,
    const int *a1_file,
    const int *a2_file,
    const double *effect,
    const double *se,
    const double *p,
    const double *n_values,
    const double *maf_ref,
    size_t n,
    const double *maf_file,
    size_t maf_file_len,
    const double *info,
    size_t info_len,
    double info_filter,
    int ols,
    int beta_is_character,
    int linprob,
    int se_logit,
    int *keep,
    double *beta,
    double *se_out,
    size_t out_len,
    int *counts,
    size_t counts_len,
    size_t *out_count);

int genomicssem_sumstats_fused(
    const char *filename,
    const char **ref_snp,
    size_t ref_len,
    const int *ref_a1,
    size_t ref_a1_len,
    const int *ref_a2,
    size_t ref_a2_len,
    const double *ref_maf,
    size_t ref_maf_len,
    const int *col_indices,
    size_t col_indices_len,
    double provided_n,
    double info_filter,
    int ols,
    int beta_is_character,
    int linprob,
    int se_logit,
    int *keep,
    double *beta,
    double *se,
    size_t out_len,
    int *out_counts,
    size_t out_counts_len,
    size_t *rows_total,
    size_t *rows_duplicate_removed,
    size_t *rows_joined,
    size_t *rows_written,
    int *unsupported);

int genomicssem_ldsc_block_products(
    const double *weighted_ld,
    size_t n_snps,
    size_t n_annot,
    const double *weighted_chi,
    size_t chi_len,
    size_t n_blocks,
    double *xty_block,
    size_t xty_block_len,
    double *xtx_block,
    size_t xtx_block_len,
    double *xty,
    size_t xty_len,
    double *xtx,
    size_t xtx_len,
    size_t n_threads);

#endif
